Update main.yaml

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -24,133 +24,126 @@ jobs:
       - name: install dependencies
         run: npm install
 
-      - name: check
-        run: tar -czvf node_modules.tar.gz node_modules/
-
-      - name: check
-        run: ls -la
-
       - name: Archive dependencies
-        uses: actions/upload-artifact@v4
+        uses: actions/upload-artifact@v4.3.5
         with:
           name: dist-without-markdown
-          path: node_modules.tar.gz
-          compression-level: 1
+          path: node_modules
       
-  lint:
-    needs: [install-dependency]
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v3
-        with:
-          fetch-depth: 0
+  # lint:
+  #   needs: [install-dependency]
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v3
+  #       with:
+  #         fetch-depth: 0
             
-      - name: Setup Node
-        uses: actions/setup-node@v3
-        with:
-          node-version: 20.15.1
-          cache: 'npm'
+  #     - name: Setup Node
+  #       uses: actions/setup-node@v3
+  #       with:
+  #         node-version: 20.15.1
+  #         cache: 'npm'
           
-      - name: Download dependencies
-        uses: actions/download-artifact@v4
-        with:
-          name: dist-without-markdown
-          path: .
+  #     - name: Download dependencies
+  #       uses: actions/download-artifact@v4
+  #       with:
+  #         name: dist-without-markdown
+  #         path: .
 
-      - run: tar -xzvf node_modules.tar.gz
+  #     - run: tar -xzvf node_modules.tar.gz
 
-      - run: ls -la
+  #     - run: ls -la
               
-      - name : Run linter
-        run: npm run lint
-  tests:
-    needs: [install-dependency]
-    strategy:
-      matrix:
-        shardIndex: [1, 2, 3, 4, 5, 6, 7, 8]
-        shardTotal: [8]
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v3
-        with:
-          fetch-depth: 0
+  #     - name : Run linter
+  #       run: npm run lint
+  # tests:
+  #   needs: [install-dependency]
+  #   strategy:
+  #     matrix:
+  #       shardIndex: [1, 2, 3, 4, 5, 6, 7, 8]
+  #       shardTotal: [8]
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v3
+  #       with:
+  #         fetch-depth: 0
           
-      - name: Setup Node
-        uses: actions/setup-node@v3
-        with:
-          node-version: 20.15.1
-          cache: 'npm'
+  #     - name: Setup Node
+  #       uses: actions/setup-node@v3
+  #       with:
+  #         node-version: 20.15.1
+  #         cache: 'npm'
           
-      - name: Download dependencies
-        uses: actions/download-artifact@v4
-        with:
-          name: dist-without-markdown
-          path: .
+  #     - name: Download dependencies
+  #       uses: actions/download-artifact@v4
+  #       with:
+  #         name: dist-without-markdown
+  #         path: .
 
-      - run: tar -xzvf node_modules.tar.gz
+  #     - run: tar -xzvf node_modules.tar.gz
 
-      - run: ls -la
+  #     - run: ls -la
         
-      - name : Test
-        run: npx cross-env CI=true vitest --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }} --coverage
+  #     - name : Test
+  #       run: npx cross-env CI=true vitest --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }} --coverage
 
-      - run: mkdir -p coverage/lcov
-      - run: mkdir -p coverage/xml
+  #     - run: mkdir -p coverage/lcov
+  #     - run: mkdir -p coverage/xml
 
-      - name: Move coverage report
-        run: mv ./tests/coverage/lcov.info coverage/lcov/${{matrix.shardIndex}}.info
+  #     - name: Move coverage report
+  #       run: mv ./tests/coverage/lcov.info coverage/lcov/${{matrix.shardIndex}}.info
         
-      - name: Move coverage report
-        run: mv ./test-report.xml coverage/xml/${{matrix.shardIndex}}.xml
+  #     - name: Move coverage report
+  #       run: mv ./test-report.xml coverage/xml/${{matrix.shardIndex}}.xml
 
-      - name: Upload artifact
-        if: ${{ !cancelled() }}
-        uses: actions/upload-artifact@v3
-        with:
-          name: coverage-artifacts
-          path: coverage/
+  #     - name: Upload artifact
+  #       if: ${{ !cancelled() }}
+  #       uses: actions/upload-artifact@v3
+  #       with:
+  #         name: coverage-artifacts
+  #         path: coverage/
         
-     # - name: Upload blob report to GitHub Actions Artifacts
-     #   if: ${{ !cancelled() }}
-     #   uses: actions/upload-artifact@v4
-     #   with:
-     #     name: blob-report-${{ matrix.shardIndex }}
-     #     path: .vitest-reports/*
-     #     include-hidden-files: true
-     #     retention-days: 1
+  #    # - name: Upload blob report to GitHub Actions Artifacts
+  #    #   if: ${{ !cancelled() }}
+  #    #   uses: actions/upload-artifact@v4
+  #    #   with:
+  #    #     name: blob-report-${{ matrix.shardIndex }}
+  #    #     path: .vitest-reports/*
+  #    #     include-hidden-files: true
+  #    #     retention-days: 1
 
-  merge-reports-and-sonar-scan:
-    if: ${{ !cancelled() }}
-    needs: [tests, lint]
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v3
+  # merge-reports-and-sonar-scan:
+  #   if: ${{ !cancelled() }}
+  #   needs: [tests, lint]
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v3
       
-      - name: Download coverage artifacts
-        uses: actions/download-artifact@v3
-        with:
-          name: coverage-artifacts
-          path: coverage
+  #     - name: Download coverage artifacts
+  #       uses: actions/download-artifact@v3
+  #       with:
+  #         name: coverage-artifacts
+  #         path: coverage
 
-      - name: Run script to merge all the xml files
-        run: | 
-          echo '<testExecutions version="1">' > test-report.xml
-          grep -vh testExecutions coverage/xml/*.xml >> test-report.xml
-          echo '</testExecutions>' >> test-report.xml
+  #     - name: Run script to merge all the xml files
+  #       run: | 
+  #         echo '<testExecutions version="1">' > test-report.xml
+  #         grep -vh testExecutions coverage/xml/*.xml >> test-report.xml
+  #         echo '</testExecutions>' >> test-report.xml
           
-      - name: Run script to merge all the lcov files
-        run: |
-            mkdir ./tests/coverage
-            cat coverage/lcov/*.info > ./tests/coverage/lcov.info
+  #     - name: Run script to merge all the lcov files
+  #       run: |
+  #           mkdir ./tests/coverage
+  #           cat coverage/lcov/*.info > ./tests/coverage/lcov.info
       
-      - name: SonarCloud Scan
-        uses: SonarSource/sonarcloud-github-action@master
-        if: success() || failure()
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+  #     - name: SonarCloud Scan
+  #       uses: SonarSource/sonarcloud-github-action@master
+  #       if: success() || failure()
+  #       env:
+  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
+  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
 
-      - run: ls -la
+  #     - run: ls -la
